layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jekyll-paginate-v2
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 3
  exclude:
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: Bryan Tee
  # linkedin: your_username
  # medium: @your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # youtube: your_username
  # vk: your_username

pagination:
  enabled: true
  collection: 'posts'
  per_page: 6
  permalink: '/page/:num/'
  sort_field: 'date'
  sort_reverse: true

collections: 

  posts:
    output: true
    permalink: "/:path/"

  digitalFabrication:
    output: true
    permalink: "/digitalFabrication/:path/"

  people:
    output: false

topics:
  
  - name: Tensorflow
    web_url: https://github.com/tensorflow
    image_url: ../images/Tensorflow_logo.png 
  
  - name: Caffe
    web_url: https://github.com/BVLC/caffe
    image_url: ../images/caffe2.png

  - name: Python
    web_url: https://github.com/python
    image_url: ../images/python.png
  
  - name: R
    image_url: ../images/R.png
  
  - name: AWS
    web_url: https://aws.amazon.com/free/?sc_channel=PS&sc_campaign=acquisition_SG&sc_publisher=google&sc_medium=ACQ-P%7CPS-GO%7CBrand%7CDesktop%7CSU%7CCore%7CCore%7CSG%7CEN%7CText&sc_content=Brand_Core_HV_e&sc_detail=aws&sc_category=Core&sc_segment=293639831497&sc_matchtype=e&sc_country=SG&s_kwcid=AL!4422!3!293639831497!e!!g!!aws&ef_id=CjwKCAjwp_zkBRBBEiwAndwD9dXvEXYS30C-UDcbSv8VD1a2loe76eIkcltkKJw9api5slL3EAd-rhoCLosQAvD_BwE:G:s
    image_url: ../images/aws.gif
  
  #- name: CSS
  #  web_url: https://github.com/topics/css
  #  image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/css/css.png

  - name: Arduino
    web_url: https://github.com/arduino/Arduino
    image_url: ../images/arduino.png

  - name: node.JS
    web_url: https://github.com/nodejs
    image_url: ../images/nodeJS.png


theme: jekyll-theme-cayman